name: 'Rolling restart Trojan instances'

on:
  workflow_dispatch:

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - id: pick_region
        env:
          REGIONS: ${{ vars.REGIONS }}
        run: |
          IFS=', ' read -r -a array <<< "$REGIONS"
          len=${#array[@]}
          idx=$(( ${{ github.run_number }} % len ))
          echo "region=${array[idx]}" >> $GITHUB_OUTPUT
      - uses: danny02/tfe-run@main
        with:
          token: ${{ secrets.HCP_TOKEN }}
          organization: ${{ vars.HCP_ORG }}
          workspace: ${{ vars.HCP_WORKSPACE }}
          replacements: |
            module.trojan["${{ steps.pick_region.outputs.region }}"].vultr_instance.proxy
            module.trojan["${{ steps.pick_region.outputs.region }}"].vultr_dns_record.ipv4
            module.trojan["${{ steps.pick_region.outputs.region }}"].vultr_dns_record.ipv6
          message: |
            Run triggered using tfe-run (run: ${{ github.run_number }})